### ISSUE TITLE
cannot open a video file!

### ISSUE THREAD

**Issue by mzolfaghari** [chuckcho/video-caffe#10]
Hi,

In installed the code successfully (with make) but when I use "make runtest" to see if everything is ok I get this error message:
.
.
.

[----------] 5 tests from VideoDataLayerTest/3, where TypeParam = caffe::GPUDevice<double>
[ RUN      ] VideoDataLayerTest/3.TestRead
E0413 17:41:19.627066 15017 io.cpp:181] Cannot open a video file=src/caffe/test/test_data/UCF-101_Rowing_g16_c03.avi
F0413 17:41:19.627207 15017 video_data_layer.cpp:77] Check failed: read_video_result Could not load src/caffe/test/test_data/UCF-101_Rowing_g16_c03.avi at frame 0.
*** Check failure stack trace: ***
    @     0x2ad8c0b91b7d  google::LogMessage::Fail()
    @     0x2ad8c0b93c7f  google::LogMessage::SendToLog()
    @     0x2ad8c0b9176c  google::LogMessage::Flush()
    @     0x2ad8c0b9451d  google::LogMessageFatal::~LogMessageFatal()
    @     0x2ad8c2debb54  caffe::VideoDataLayer<>::DataLayerSetUp()
    @     0x2ad8c2de1f03  caffe::BasePrefetchingDataLayer<>::LayerSetUp()
    @           0x473e6f  caffe::Layer<>::SetUp()
    @           0x5a057a  caffe::VideoDataLayerTest_TestRead_Test<>::TestBody()
    @           0x87ace3  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x8719c7  testing::Test::Run()
    @           0x871a6e  testing::TestInfo::Run()
    @           0x871b75  testing::TestCase::Run()
    @           0x874eb8  testing::internal::UnitTestImpl::RunAllTests()
    @           0x875147  testing::UnitTest::Run()
    @           0x4620af  main
    @     0x2ad8c3cf4ec5  (unknown)
    @           0x469559  (unknown)
make: *** [runtest] Aborted (core dumped)

with ignoring the above error in "make runtest" , I tried to run examples/c3d_ucf101/ but it gives this error:

I0413 17:41:36.732921 51985 video_data_layer.cpp:53] Shuffling data
I0413 17:41:36.746111 51985 video_data_layer.cpp:58] A total of 107258 video chunks.
E0413 17:41:36.804961 51985 io.cpp:181] Cannot open a video file=/misc/Dataset/UCF101/DB/PlayingCello/v_PlayingCello_g13_c02.avi
F0413 17:41:36.805089 51985 video_data_layer.cpp:77] Check failed: read_video_result Could not load /misc/Dataset/UCF101/DB/PlayingCello/v_PlayingCello_g13_c02.avi at frame 97.
*** Check failure stack trace: ***
    @     0x7fb2f2b48b7d  google::LogMessage::Fail()
    @     0x7fb2f2b4ac7f  google::LogMessage::SendToLog()
    @     0x7fb2f2b4876c  google::LogMessage::Flush()
    @     0x7fb2f2b4b51d  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fb2f31f6804  caffe::VideoDataLayer<>::DataLayerSetUp()
    @     0x7fb2f31ebd33  caffe::BasePrefetchingDataLayer<>::LayerSetUp()
    @     0x7fb2f3290cb5  caffe::Net<>::Init()
    @     0x7fb2f3291d65  caffe::Net<>::Net()
    @     0x7fb2f313201a  caffe::Solver<>::InitTrainNet()
    @     0x7fb2f313312c  caffe::Solver<>::Init()
    @     0x7fb2f313345a  caffe::Solver<>::Solver()
    @     0x7fb2f326a373  caffe::Creator_SGDSolver<>()
    @           0x40fdae  caffe::SolverRegistry<>::CreateSolver()
    @           0x409160  train()
    @           0x406bbc  main
    @     0x7fb2f1a17ec5  (unknown)
    @           0x4072f1  (unknown)

I checked the system for opencv and ffmpeg and everything seems is working!. I don't have any idea what's the problem. 

Regards,
--
Reza

**Comment by chuckcho** [comment]
Hmm. `make runtest` should pass as it is in Travis (https://travis-ci.org/chuckcho/video-caffe). So, I would have to suspect opencv is not behaving.

**Comment by haohao900618** [comment]
@mzolfaghari I encountered the same problem like you. I want to know how did you solve it? Thank you very much!

**Comment by chuckcho** [comment]
Will revisit if this continues to occur.

**Comment by nvanthuy** [comment]
I have the same problem now. I am running with mode: CPU_ONLY=1, no Cudnn (use_CUDNN=0) since my laptop don't have GPU card, does this cause the problem? Any suggestion? Thank you.

**Comment by chuckcho** [comment]
@nvanthuy Currently `video-caffe` requires a GPU (CUDA/CuDNN)

**Comment by deepaksharma36** [comment]
I am also experiencing the same issue, @haohao900618 how did you manage to fix it?

**Comment by ljpadam** [comment]
I met the same problem. @chuckcho How could we solve this?
