### ISSUE TITLE
Dockerfile should be updated

### ISSUE THREAD

**Issue by huangyz0918** [chuckcho/video-caffe#106]
### Issue summary
The Dockerfile should be update since the github address is BVLC's caffe, not video_caffe.
If we use the docker to run video_caffe, something will go wrong (e.g,  "caffe.LayerParameter" has no field named "video_data_param", because the docker image is not ours.).

I tried several times to install this video_caffe by docker, nothing goes wrong during the whole installation progress, but I cannot find `"video_data_param"` because this is BVLC's image, not yours.

**Comment by chuckcho** [comment]
thanks for your contribution. will merge.
