### ISSUE TITLE
How to extract features

### ISSUE THREAD

**Issue by dehaisea** [chuckcho/video-caffe#12]
When running the 'feature_extractor.sh', 'c3d_ucf101_test.prototxt' will read two files 'videos_live_input.txt' and 'videos_live_patch_input.txt', but I can't find these two files. Would you like to upload these two files or show me how to modify them? Thank you.

**Comment by attitudechunfeng** [comment]
You needn't follow the input style of 'c3d_ucf101_test.prototxt', actually, it's just an example. In the example, I write a siamese network so there're two inputs layer. Ordinarily, you just need one input layer and the 'txt file' should follows the pattern as below:
_path start_frame label_
_path start_frame label_
_path start_frame label_
...

**Comment by ParitoshParmar** [comment]
@attitudechunfeng From training prototxt file, your network is not siamese. I was just wondering how were you extracting features for pairs of input images ? Also, if you have tested C3D features in a siamese setting, could you please let me know about the performance ?

**Comment by hawklucky** [comment]
Did the extract_feature.sh work?

**Comment by ParitoshParmar** [comment]
@hawklucky Yes, the extract_feature.sh works. What problem are you facing?

**Comment by hawklucky** [comment]
When I exe the extract_feature.sh, it comes out this:
E1006 21:09:13.477331 26461 predict.cpp:55] Extracting features for 41822 batches
W1006 21:09:13.477407 26461 net.cpp:580] DEPRECATED: Forward(bottom, loss) will be removed in a future version. Use Forward(loss).
I1006 21:09:13.477432 26461 blocking_queue.cpp:50] Data layer prefetch queue empty
E1006 21:09:18.556071 26461 predict.cpp:95] Successfully extracted 0 features!

**Comment by ParitoshParmar** [comment]
@hawklucky Are you giving the correct path of the source file in the 'test.prototxt', and correct path to videos in the source file? (You will have to modify the addresses according to your directory) 

Predict.cpp will say the number of successfully extracted features at an interval of 100*batch_size, but since in your case, it says successfully extracted 0 features, so I was wondering if your input list is empty by any chance ?

**Comment by hawklucky** [comment]
Yes, I check the path that is correct, the 41822 is the test_split1 clips num.
I1007 22:01:35.097631  9845 video_data_layer.cpp:39] Opening file examples/c3d_ucf101/c3d_ucf101_test_modify_split1.txt
I1007 22:01:35.114215  9845 video_data_layer.cpp:58] A total of 41822 video chunks.

**Comment by pelun** [comment]
When I run extract_UCF-101_frames.sh. Command window shows: File "extract_UCF-101_frames.sh", line 5
    UCF101DIR=/home/.../examples/video
                        ^
SyntaxError: invalid syntax
I hope everyone can help me, please.

**Comment by chuckcho** [comment]
looks like you have extra spaces around `=`. this shoudl be `UCF101DIR=/home/.../examples/video`

**Comment by pelun** [comment]
I fixed. But it still happen error.

**Comment by hawklucky** [comment]
Is that I extract fc8 features for the linear svm classification? Which blob should I extract if I want to use the blob feature to represent the video? THANKS.@chukcho

**Comment by chuckcho** [comment]
shell-related issue. closing.
