### ISSUE TITLE
Accuracy of UCF101 Training

### ISSUE THREAD

**Issue by cteckwee** [chuckcho/video-caffe#13]
Thanks for the good work. I just managed to port your code to Visual Studio 2013 in Windows 10. Currently, the training is still ongoing. At iteration 1000:

test net output #0 accuracy/top-1 = 0.034,  
test net output #1 accuracy/top-5 = 0.12
test net output #2 loss =4.49625

Is the output normal? 

I would like to know also what is your final accuracy and roughly how long it takes to train UCF dataset. I am using Quadro K6000 graphics card with 12GB RAM and 2880 cuda cores.

Thanks in advance.

**Comment by chuckcho** [comment]
That looks normal to me, but it's too early to tell.

After 27hrs of training on GTX Titan Black with 6GB mem, I get **35%** top-1 accuracy at Iteration 60,000=8.4 epochs (60,000/107,258*15). This is somehow not on a par with the original facebook/C3D implementation, which got ~44% (Fig. 2 in the [original paper](https://arxiv.org/pdf/1412.0767.pdf)) I'm investigating why this is the case.

**Comment by cteckwee** [comment]
Hi thanks, 27 hours doesn't seem too bad. My training randomly crash at different iteration during evaluation/test phase (one time at iter 1000 and another time at iter 5000), there is no error message in the log file. I use the default solver and prototxt parameters as yours and my GPU memory is definitely sufficient. Could it be because there is problem with test video input reading problem? I did not convert the videos as image frames. In the mean time, I will read the original paper to investigate the lower performance problem.

**Comment by chuckcho** [comment]
Yes, directly accessing videos may well be the cause for crashes. I have seen some weird behavior with that (but no hard crash though). Feel free to use [this script](https://github.com/chuckcho/video-caffe/blob/master/examples/c3d_ucf101/extract_UCF-101_frames.sh) to extract frames from videos.

**Comment by cteckwee** [comment]
May I know after I extracted the avi to jpeg images, do I need to change "c3d_ucf101_train_split1.txt"? It seems that this text file only contain .avi but not .jpg filenames.

**Comment by chuckcho** [comment]
Yes. Just specify the directory (the extracted frames are located). So, deleting ".avi" in each line of the train/test files will do it.

**Comment by cteckwee** [comment]
Thanks I will give it a try. May be problematic to run your sh script as I am running on Windows.

**Comment by chuckcho** [comment]
Ah Windows! :smile: Good luck!

**Comment by cteckwee** [comment]
Cygwin comes to rescue :) Managed to extract all the frames using your script.

**Comment by cteckwee** [comment]
Seems like converting video to images solve the random crash problem. I just passed 41000 iteration and now the results are:
Test-on-train:
top-1=  95.2%  top-5= 99.3%

Test-on-val:
top-1 = 37.1%     top-5 = 60.0%  

I believe the accuracy will be further improved when reaching 60000 iterations.

I notice that you are using less number of filters for group 4 and group 5 (256 vs 512) and half full connected layers fc6 and fc7 (2048 vs 4096). Could this causing the performance drop compared to the original paper?

**Comment by chuckcho** [comment]
:+1: Good to know that. Let me know the final top-1 accuracy when you're done training. Thx.

**Comment by cteckwee** [comment]
Unfortunately the accuracy went down after 40,000 iterations, top-1 accuracy is about 33% when reaching 60,000 iterations. I am retraining with network parameters similar to the original paper: group 4 and group 5 (512 filters) and half full connected layers fc6 and fc7 (4096). At this juncture of 50,000 iterations the top-1 accuracy is 36.8% only.

**Comment by ParitoshParmar** [comment]
The original paper uses 2 convolutional layers at 5 stage: conv5a and conv5b, but this implementation uses one - conv5a layer, that might be a reason for the difference in the results.

**Comment by chuckcho** [comment]
I debugged the code, and it should be able to converge and match the performance as in the original paper. See https://github.com/chuckcho/video-caffe/blob/master/examples/c3d_ucf101/README.md for detail.
