### ISSUE TITLE
labels should be a 5-d array (pycaffe)

### ISSUE THREAD

**Issue by hccheng** [chuckcho/video-caffe#14]
With the additional temporal dimension, labels sent through pycaffe should be a 5-d array (instead of 4).

pycaffe.py, line 257:
`labels = np.ascontiguousarray(labels[:, np.newaxis, np.newaxis, np.newaxis])`

should be changed into
`labels = np.ascontiguousarray(labels[:, np.newaxis, np.newaxis, np.newaxis, np.newaxis])`

**Comment by chuckcho** [comment]
Thx. Commited.
