### ISSUE TITLE
Check failed: mdb_status == 0 (-30782 vs. 0) 

### ISSUE THREAD

**Issue by ruizhaogit** [chuckcho/video-caffe#16]
Hi,

Does anyone have the same runtest error with lmdb? 

[----------] 5 tests from DBTest/1, where TypeParam = caffe::TypeLMDB
[ RUN      ] DBTest/1.TestSeekToFirst
[       OK ] DBTest/1.TestSeekToFirst (80 ms)
[ RUN      ] DBTest/1.TestNext
[       OK ] DBTest/1.TestNext (81 ms)
[ RUN      ] DBTest/1.TestWrite
F0603 10:22:00.916103   650 db_lmdb.hpp:15] Check failed: mdb_status == 0 (-30782 vs. 0) MDB_BAD_TXN: Transaction cannot recover - it must be aborted
*** Check failure stack trace: ***
    @     0x7f80a49c240d  google::LogMessage::Fail()
    @     0x7f80a49c42cf  google::LogMessage::SendToLog()
    @     0x7f80a49c1fa3  google::LogMessage::Flush()
    @     0x7f80a49c4bee  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f80a5598be6  caffe::db::LMDBTransaction::Commit()
    @     0x7f80a5598a78  caffe::db::LMDBTransaction::Commit()
    @           0x9eddbb  caffe::DBTest_TestWrite_Test<>::TestBody()
    @           0xde6c93  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0xddd567  testing::Test::Run()
    @           0xddd60e  testing::TestInfo::Run()
    @           0xddd715  testing::TestCase::Run()
    @           0xde0448  testing::internal::UnitTestImpl::RunAllTests()
    @           0xde06e7  testing::UnitTest::Run()
    @           0x8c23ef  main
    @     0x7f80958a0b05  __libc_start_main
    @           0x8c9692  (unknown)
/bin/sh: line 1:   650 Aborted                 /home_local/C3D/new/video-caffe/build/test/test.testbin --gtest_shuffle
src/caffe/test/CMakeFiles/runtest.dir/build.make:57: recipe for target 'src/caffe/test/CMakeFiles/runtest' failed
make[3]: *** [src/caffe/test/CMakeFiles/runtest] Error 134
CMakeFiles/Makefile2:328: recipe for target 'src/caffe/test/CMakeFiles/runtest.dir/all' failed
make[2]: *** [src/caffe/test/CMakeFiles/runtest.dir/all] Error 2
CMakeFiles/Makefile2:335: recipe for target 'src/caffe/test/CMakeFiles/runtest.dir/rule' failed
make[1]: *** [src/caffe/test/CMakeFiles/runtest.dir/rule] Error 2
Makefile:240: recipe for target 'runtest' failed
make: *** [runtest] Error 2

**Comment by chuckcho** [comment]
Hmm. Haven't seen this before. Does BVLC/caffe build and runtest fine?

**Comment by ruizhaogit** [comment]
Yeah, the standard version pass all the runtest.

**Comment by chuckcho** [comment]
Beats me at this point. My `runtest` came out fine. Is DBTest the only fail?

**Comment by ruizhaogit** [comment]
It stoped by the DBTest. Plenty of the previous tests were fine. I mean if I just feed the videos or frames to the model, I don't need lmdb, right?

**Comment by chuckcho** [comment]
You don't need lmdb. BTW, something like `cd build && make test.testbin && cd .. && build/test/test.testbin --gtest_filter=-*DBTest*` will bypass DBTest*.

**Comment by ruizhaogit** [comment]
Bypass DBTest, then get this error:

[----------] 12 tests from SGDSolverTest/0, where TypeParam = caffe::CPUDevice<float>
[ RUN      ] SGDSolverTest/0.TestLeastSquaresUpdate
F0603 15:06:02.260300 31309 hdf5_data_layer.cpp:88] Failed to open source file: src/caffe/test/test_data/solver_data_list.txt
*** Check failure stack trace: ***
    @     0x7f7c35fa740d  google::LogMessage::Fail()
    @     0x7f7c35fa92cf  google::LogMessage::SendToLog()
    @     0x7f7c35fa6fa3  google::LogMessage::Flush()
    @     0x7f7c35fa9bee  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f7c36c2b201  caffe::HDF5DataLayer<>::LayerSetUp()
    @     0x7f7c36beb595  caffe::Net<>::Init()
    @     0x7f7c36bec435  caffe::Net<>::Net()
    @     0x7f7c36bfa3fa  caffe::Solver<>::InitTrainNet()
    @     0x7f7c36bfb60c  caffe::Solver<>::Init()
    @     0x7f7c36bfb93a  caffe::Solver<>::Solver()
    @           0xaa1c64  caffe::SGDSolverTest<>::InitSolver()
    @           0xaa23e0  caffe::GradientBasedSolverTest<>::InitSolverFromProtoString()
    @           0xa61586  caffe::GradientBasedSolverTest<>::RunLeastSquaresSolver()
    @           0xa65d26  caffe::GradientBasedSolverTest<>::TestLeastSquaresUpdate()
    @           0xde6c93  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0xddd567  testing::Test::Run()
    @           0xddd60e  testing::TestInfo::Run()
    @           0xddd715  testing::TestCase::Run()
    @           0xde0448  testing::internal::UnitTestImpl::RunAllTests()
    @           0xde06e7  testing::UnitTest::Run()
    @           0x8c23ef  main
    @     0x7f7c26e85b05  __libc_start_main
    @           0x8c9692  (unknown)
Aborted

**Comment by chuckcho** [comment]
@ruizhaogit I have a feeling that you're running `test.testbin` inside `build` directory. It needs to be run in video-caffe root dir.

**Comment by ruizhaogit** [comment]
You are right. 
All the other tests are passed, except DBTest.

[----------] 2 tests from Im2colKernelTest/1, where TypeParam = double
[ RUN      ] Im2colKernelTest/1.Test2D
[       OK ] Im2colKernelTest/1.Test2D (51 ms)
[ RUN      ] Im2colKernelTest/1.TestND
[       OK ] Im2colKernelTest/1.TestND (60 ms)
[----------] 2 tests from Im2colKernelTest/1 (111 ms total)

[----------] Global test environment tear-down
[==========] 2039 tests from 273 test cases ran. (379816 ms total)
[  PASSED  ] 2039 tests.

**Comment by chuckcho** [comment]
In that case, please ignore "DBTest" error. :)

**Comment by ruizhaogit** [comment]
Sure, thank you!
