### ISSUE TITLE
Runtest error: [  FAILED  ] CuDNNConvolutionLayerTest/0.TestGradientGroupCuDNN, where TypeParam = float (2656 ms)

### ISSUE THREAD

**Issue by ruizhaogit** [chuckcho/video-caffe#19]
Hi @chuckcho,

I buiit the video_caffe with cuDNN 4.0.07 and CUDA 8.0, got runtest error as following.

Do you have any idea how to solve this one?

Thank you!

/home_local/C3D/new/video-caffe/include/caffe/test/test_gradient_check_util.hpp:175: Failure
The difference between computed_gradient and estimated_gradient is 185.08511812984943, which exceeds threshold_ * scale, where
computed_gradient evaluates to 0.2218368798494339,
estimated_gradient evaluates to -184.86328125, and
threshold_ * scale evaluates to 0.18486328423023224.
debug: (top_id, top_data_id, blob_id, feat_id)=0,11,2,137; feat = -0.42774304747581482; objective+ = 15435.001953125; objective- = 15438.69921875
/home_local/C3D/new/video-caffe/include/caffe/test/test_gradient_check_util.hpp:175: Failure
The difference between computed_gradient and estimated_gradient is 187.02707886695862, which exceeds threshold_ * scale, where
computed_gradient evaluates to 2.1637976169586182,
estimated_gradient evaluates to -184.86328125, and
threshold_ * scale evaluates to 0.18486328423023224.
debug: (top_id, top_data_id, blob_id, feat_id)=0,11,2,138; feat = 1.5978063344955444; objective+ = 15442.396484375; objective- = 15446.09375
/home_local/C3D/new/video-caffe/include/caffe/test/test_gradient_check_util.hpp:175: Failure
The difference between computed_gradient and estimated_gradient is 184.86328125, which exceeds threshold_ * scale, where
computed_gradient evaluates to 0,
estimated_gradient evaluates to -184.86328125, and
threshold_ * scale evaluates to 0.18486328423023224.
debug: (top_id, top_data_id, blob_id, feat_id)=0,11,2,139; feat = 0.36233514547348022; objective+ = 15449.791015625; objective- = 15453.48828125
/home_local/C3D/new/video-caffe/include/caffe/test/test_gradient_check_util.hpp:175: Failure
The difference between computed_gradient and estimated_gradient is 184.86328125, which exceeds threshold_ * scale, where
computed_gradient evaluates to 0,
estimated_gradient evaluates to -184.86328125, and
threshold_ * scale evaluates to 0.18486328423023224.
debug: (top_id, top_data_id, blob_id, feat_id)=0,11,2,140; feat = -1.1225214004516602; objective+ = 15457.185546875; objective- = 15460.8828125
/home_local/C3D/new/video-caffe/include/caffe/test/test_gradient_check_util.hpp:175: Failure
The difference between computed_gradient and estimated_gradient is 184.86328125, which exceeds threshold_ * scale, where
computed_gradient evaluates to 0,
estimated_gradient evaluates to -184.86328125, and
threshold_ * scale evaluates to 0.18486328423023224.
debug: (top_id, top_data_id, blob_id, feat_id)=0,11,2,141; feat = 1.9254717826843262; objective+ = 15464.580078125; objective- = 15468.27734375
/home_local/C3D/new/video-caffe/include/caffe/test/test_gradient_check_util.hpp:175: Failure
The difference between computed_gradient and estimated_gradient is 184.86328125, which exceeds threshold_ * scale, where
computed_gradient evaluates to 0,
estimated_gradient evaluates to -184.86328125, and
threshold_ * scale evaluates to 0.18486328423023224.
debug: (top_id, top_data_id, blob_id, feat_id)=0,11,2,142; feat = -0.16014505922794342; objective+ = 15471.974609375; objective- = 15475.671875
/home_local/C3D/new/video-caffe/include/caffe/test/test_gradient_check_util.hpp:175: Failure
The difference between computed_gradient and estimated_gradient is 184.86328125, which exceeds threshold_ * scale, where
computed_gradient evaluates to 0,
estimated_gradient evaluates to -184.86328125, and
threshold_ * scale evaluates to 0.18486328423023224.
debug: (top_id, top_data_id, blob_id, feat_id)=0,11,2,143; feat = 2.3212559223175049; objective+ = 15479.369140625; objective- = 15483.06640625

[  FAILED  ] CuDNNConvolutionLayerTest/0.TestGradientGroupCuDNN, where TypeParam = float (2656 ms)

[----------] Global test environment tear-down
[==========] 2039 tests from 273 test cases ran. (310461 ms total)
[  PASSED  ] 2034 tests.
[  FAILED  ] 5 tests, listed below:
[  FAILED  ] CuDNNConvolutionLayerTest/0.TestSimpleConvolutionCuDNN, where TypeParam = float
[  FAILED  ] CuDNNConvolutionLayerTest/0.TestSimpleConvolutionGroupCuDNN, where TypeParam = float
[  FAILED  ] CuDNNConvolutionLayerTest/0.TestSobelConvolutionCuDNN, where TypeParam = float
[  FAILED  ] CuDNNConvolutionLayerTest/0.TestGradientCuDNN, where TypeParam = float
[  FAILED  ] CuDNNConvolutionLayerTest/0.TestGradientGroupCuDNN, where TypeParam = float

 5 FAILED TESTS

**Comment by ruizhaogit** [comment]
@chuckcho, can your mdel be compiled without cuDNN?

**Comment by chuckcho** [comment]
At least, it now builds and works with cuDNN v5. Haven't got into CUDA 8.0 yet. Will merge upstream (BVLC) when CUDA 8.0 becomes official.
