### ISSUE TITLE
Integrate the video data layer into the official master branch

### ISSUE THREAD

**Issue by futurely** [chuckcho/video-caffe#22]
From my incomplete understanding of this repository, C3D model [training](https://github.com/chuckcho/video-caffe/blob/master/examples/c3d_ucf101/c3d_ucf101_train_test.prototxt) requires three new layers that the old Caffe didn't have: video data, nd convolution and nd pooling. The latter two have the chance to a part of the official master branch given that https://github.com/BVLC/caffe/pull/3983 is almost completed. Regarding the the video data layer, the implementation of facebook/C3D was based on a much earlier version of Caffe and it's probably much more difficult to migrate to the latest version. The functionalities of that implementation and your implementation are basically the same, but I haven't compared every detail. Would you like to send a PR to integrate the video data layer and other C3D related work? After that, you wouldn't have to manually update Caffe any more.

**Comment by futurely** [comment]
Tried to extract all the video data layer related changes into a single commit. All the 2117 tests from 283 test cases passed.
[video_data_layer.diff.txt](https://github.com/chuckcho/video-caffe/files/333555/video_data_layer.diff.txt)

**Comment by chuckcho** [comment]
will check this after returning from CVPR. Thanks for your contribution.

**Comment by vuptran** [comment]
I second this PR as I use the video_data layer frequently for video applications. Integrating it into the official master branch would see a lot of good use out of it. Would it be possible to have the layer handle arbitrary volume data (e.g., 3D MRI scans), not just video data?

**Comment by chuckcho** [comment]
Good comment! Will do it when I have some spare time.
