### ISSUE TITLE
what do I need to change if I extracted frames than directly with video files

### ISSUE THREAD

**Issue by mrxue1993** [chuckcho/video-caffe#28]
Hi, sorry to bother you, I just not sure what I need to change for 
${video-caffe-root}/examples/c3d_ucf101/c3d_ucf101_{train,test}_split1.txt
if I extract frames from the video, for the video method, it is
```
/media/TB/Videos/UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c01.avi 1 0
/media/TB/Videos/UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c01.avi 17 0
/media/TB/Videos/UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c01.avi 33 0
/media/TB/Videos/UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c01.avi 49 0
/media/TB/Videos/UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c01.avi 65 0
/media/TB/Videos/UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c01.avi 81 0
/media/TB/Videos/UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c01.avi 97 0
/media/TB/Videos/UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c02.avi 1 0
```
so after I extract frames, each directory will contain 16 images instead of a .avi video?
also, do I need to modify something in the 
${video-caffe-root}/examples/c3d_ucf101/c3d_ucf101_train_test.prototxt ?
to be specific, I mean the first layer
```
# ----- video/label input -----
# ----- for training
layer {
  name: "data"
  type: "VideoData"
  top: "data"
  top: "label"
  video_data_param {
    source: "examples/c3d_ucf101/c3d_ucf101_train_split1.txt"
    batch_size: 15
    new_height: 128
    new_width: 171
    new_length: 16
    shuffle: true
  }
  include {
    phase: TRAIN
  }
  transform_param {
    crop_size: 112
    mirror: true
    mean_file: "examples/c3d_ucf101/ucf101_train_mean.binaryproto"
  }
}
```

**Comment by mrxue1993** [comment]
can someone help me answer the question? I really need it, thanks

**Comment by ParitoshParmar** [comment]
You don't need to extract images, it works well with video. The nos. indicate the starting frame no. The network by default considers consecutive 16 frames. You are ready to run the network. Let me know if this doesn't answer your question.

**Comment by mrxue1993** [comment]
I understand that it works well with video, just want to know what adjustment I need to make to if I extract frames from the video as advised by chuckcho

**Comment by ParitoshParmar** [comment]
You need to make changes in input file list as per the original C3D code, but I guess chuckcho included that suggestion just to warn the users against potential instability, otherwise I don't see any difference.

Original C3D code input file difference:
frame as input: directory/input/frm/v_ApplyEyeMakeup_g01_c01/ 1 0 (first frame)
video as input: directory/input/avi/v_ApplyEyeMakeup_g01_c01.avi 0 0 (starts at zeroth frame, although you can change this).

Hope this clears your doubt.

**Comment by chuckcho** [comment]
Sorry for the delay -- I used 1-based indexing for both video files or directory containing extracted frames -- see https://github.com/chuckcho/video-caffe/blob/master/src/caffe/util/io.cpp#L160-L255 and modify as you see fit.
