### ISSUE TITLE
cudnn_ndconv_layer.cpp: Not Implemented Yet

### ISSUE THREAD

**Issue by fxing328** [chuckcho/video-caffe#30]
Hi, 

I just trying to train the model on UCF101, I'm running this on GPU cluster,  but I met a problem saying: cudnn_ndconv_layer.cpp:255: 
Not Implemented Yet. 

The detail problem is as following:
......
I0712 22:18:05.019098  9260 net.cpp:219] data does not need backward computation.
I0712 22:18:05.019101  9260 net.cpp:261] This network produces output loss
I0712 22:18:05.019116  9260 net.cpp:274] Network initialization done.
I0712 22:18:05.019204  9260 solver.cpp:60] Solver scaffolding done.
100
> /scratch/xf362/video-caffe/examples/c3d_ucf101/train_ucf101.py(79)<module>()
-> solver.step(1)  # SGD by Caffea
(Pdb) n
F0712 22:18:09.631315  9260 cudnn_ndconv_layer.cpp:255] Not Implemented Yet
*** Check failure stack trace: ***
Aborted

Any suggestion on this problem?

**Comment by chuckcho** [comment]
is CUDA and CUDNN enabled? The error occurs when CPU is being used for NdConv

**Comment by icbcbicc** [comment]
I encounter the same problem when I  try to test the model without GPU. But when I use GPU to test this model, it works fine.

**Comment by chuckcho** [comment]
@fxing328 @icbcbicc please bear with me. i'm refactoring the code so that it's not dependent on CUDA.

**Comment by fxing328** [comment]
I just fix the problem. Yes, it is because I didn't enable the gpu_mode,  the running was actually in cpu mode.  Now it works. Thanks!
