### ISSUE TITLE
How to provide 2 input files to VideoData layer for a siamese network ?

### ISSUE THREAD

**Issue by ParitoshParmar** [chuckcho/video-caffe#33]
I want to implement a siamese network but with VideoData. So, how can I specify the pair of input clips in the input_list.txt ?

**Comment by chuckcho** [comment]
Haven't tried siamese. It seems that you'll need to write data-prep tool (something like [/examples/siamese/convert_mnist_siamese_data.cpp](https://github.com/chuckcho/video-caffe/tree/master/examples/siamese/convert_mnist_siamese_data.cpp) for a video).
