### ISSUE TITLE
Clip accuracy discrepancy

### ISSUE THREAD

**Issue by cteckwee** [chuckcho/video-caffe#34]
Hi Chuckcho, I'm glad that now clip-based accuracy can achieve 45% (as per Figure 2 in original paper). However, in that paper Table 3 the accuracy is much higher >80%. 

Based on the reply from the original author, DuTran (https://github.com/facebook/C3D/issues/136), he stated that >80% accuracy is clip-based but not video-based. 

I'm quite confuse with this, may I know what is your view on this?

**Comment by chuckcho** [comment]
https://github.com/facebook/C3D/issues/136 discusses finetuning results (from sports1m data I believe), not training from scratch whereas 45% clip accuracy comes from training from scratch. Hope it clears up your confusion.

**Comment by cteckwee** [comment]
Thank you for your reply.
