### ISSUE TITLE
How to analyze trained result?

### ISSUE THREAD

**Issue by JinJunho** [chuckcho/video-caffe#37]
What should I plot to analyze the trained data or test result?

**Comment by chuckcho** [comment]
Can you be more specific?  To monitor training, you can plot train (or test) loss or test accuracy. [/tools/extra/parse_log.py](https://github.com/chuckcho/video-caffe/blob/master/tools/extra/parse_log.py), for example, parses log file. And, [/tools/extra/plot_training_log.py.example](https://github.com/chuckcho/video-caffe/blob/master/tools/extra/plot_training_log.py.example) script plots parsed log. This is really `caffe` question, so please use caffe newsgroup for more info -- https://groups.google.com/forum/#!forum/caffe-users.

**Comment by chuckcho** [comment]
Closed as it's not `video-caffe`-specific.
