### ISSUE TITLE
.build_release/src/caffe/layer_factory.o Error 1

### ISSUE THREAD

**Issue by zhangzhenyuan** [chuckcho/video-caffe#39]
Dear chuckcho:

   I have installed CUDA7.5 and cudnn-7.5-linux-x64-v5.0 on my PC which has no GPU. This is my makefile.config:
![qq 20160912172916](https://cloud.githubusercontent.com/assets/6830015/18431190/7d504e4c-790e-11e6-83b6-df2142dbdd24.jpg)

 An error occurred as follows:
![2](https://cloud.githubusercontent.com/assets/6830015/18432754/69b0c4cc-7916-11e6-89c2-abb6ab7a8f31.jpg)

![1](https://cloud.githubusercontent.com/assets/6830015/18431249/ba6cec68-790e-11e6-9504-25de95bb0a89.jpg)

By the way, Does vedio-caffe support GTX 1080 which requires CUDA 8.0?

Thanks very much!

**Comment by chuckcho** [comment]
Sorry. It needs GPU (CUDA and CuDNN). I haven't tested CUDA 8 yet -- it's likely to break something.

**Comment by zhangzhenyuan** [comment]
@chuckcho  Thanks so much for response. If I build with GPU support (#CPU_ONLY := 1), it can be compiled successfully. Therefore, GPU is necessary for vedio-caffe. After receiving my GTX 1080, I will have a test.

**Comment by chuckcho** [comment]
Let me know you run into a problem. Meanwhile, I'll have this issue closed for now.
