### ISSUE TITLE
Different outputs for the same input 

### ISSUE THREAD

**Issue by ParitoshParmar** [chuckcho/video-caffe#40]
I am seeing different values for FC6 layer output, during test phase, for the same input. 

Is this normal ? What could possibly be the reason for this ?

Thank you.

**Comment by chuckcho** [comment]
Hmm. If `shuffle` is off, I don't think there should be anything random.

**Comment by ParitoshParmar** [comment]
@chuckcho Just realized that the `mirror` was set to true and I am collecting the outputs before computing the final value. Also, I am working with very small no. of samples. Due to these factors, the results were varying for the same input. After turn off the `mirror`, the results are same. But thank you!

**Comment by chuckcho** [comment]
Glad it was resolved. :)
