### ISSUE TITLE
Hoes does the network calculates the video accuracy (UCF101)?

### ISSUE THREAD

**Issue by Amschel** [chuckcho/video-caffe#41]
From my understanding, we split the videos in frames and then insert groups of 16 frames as input. So when we do a test after an epoch we get the clip accuracy (for the 16 frames). Is it right? So how do the network calculates the entire video accuracy? Is it doing  the mean for class 1 the mean for class 2 and so on and then the class with the biggest mean value wins

**Comment by chuckcho** [comment]
Your understanding of clip accuracy is correct -- it's based on 16-frame clips. As far as I can see in the original paper (https://arxiv.org/pdf/1412.0767.pdf), video-level accuracy is based on averaging `fc6` layer features over all clips in a video, and using SVM for classification. So, it's a bit more involved calculation than clip-level accuracy.

**Comment by Amschel** [comment]
Thanks for prompt response. So basically we can't get the video-level accuracy directly thru video - caffe project, right?

**Comment by chuckcho** [comment]
not via `tools/caffe`. it will be a matter of python (or C++) script to do averaging and SVM.
