### ISSUE TITLE
OpenCV error when: make runtest 

### ISSUE THREAD

**Issue by lood339** [chuckcho/video-caffe#43]
Hi,
   I have an OpenCV error when I do make runtest.
  OpenCV Error: Unspecified error (GStreamer: your gstreamer installation is missing a required plugin
) in handlemessage, file /cs/public/src/opencv-3.0.0/modules/videoio/src/cap_gstreamer.cpp, line 1622
unknown file: Failure
C++ exception with description "/cs/public/src/opencv-3.0.0/modules/videoio/src/cap_gstreamer.cpp:1622: error: (-2) GStreamer: your gstreamer installation is missing a required plugin  in function handlemessage " thrown in the test body.
 As a result, there are 23 failed tests.

[  FAILED  ] 23 tests, listed below:

[  FAILED  ] IOTest.TestReadVideoToCVMatFromAviBasic

[  FAILED  ] IOTest.TestReadVideoToCVMatFromAviResize

[  FAILED  ] IOTest.TestReadVideoToCVMatFromAviResizeAndGrayscale

[  FAILED  ] VideoDataLayerTest/0.TestResize, where TypeParam = caffe::CPUDevice<float>

[  FAILED  ] VideoDataLayerTest/0.TestShuffle, where TypeParam = caffe::CPUDevice<float>

[  FAILED  ] VideoDataLayerTest/0.TestRead, where TypeParam = caffe::CPUDevice<float>

[  FAILED  ] VideoDataLayerTest/0.TestCrop, where TypeParam = caffe::CPUDevice<float>

[  FAILED  ] VideoDataLayerTest/0.TestReshape, where TypeParam = caffe::CPUDevice<float>

[  FAILED  ] VideoDataLayerTest/1.TestShuffle, where TypeParam = caffe::CPUDevice<double>

[  FAILED  ] VideoDataLayerTest/1.TestReshape, where TypeParam = caffe::CPUDevice<double>

[  FAILED  ] VideoDataLayerTest/1.TestResize, where TypeParam = caffe::CPUDevice<double>

[  FAILED  ] VideoDataLayerTest/1.TestCrop, where TypeParam = caffe::CPUDevice<double>

[  FAILED  ] VideoDataLayerTest/1.TestRead, where TypeParam = caffe::CPUDevice<double>

[  FAILED  ] VideoDataLayerTest/2.TestRead, where TypeParam = caffe::GPUDevice<float>

[  FAILED  ] VideoDataLayerTest/2.TestReshape, where TypeParam = caffe::GPUDevice<float>

[  FAILED  ] VideoDataLayerTest/2.TestResize, where TypeParam = caffe::GPUDevice<float>

[  FAILED  ] VideoDataLayerTest/2.TestCrop, where TypeParam = caffe::GPUDevice<float>

[  FAILED  ] VideoDataLayerTest/2.TestShuffle, where TypeParam = caffe::GPUDevice<float>

[  FAILED  ] VideoDataLayerTest/3.TestRead, where TypeParam = caffe::GPUDevice<double>

[  FAILED  ] VideoDataLayerTest/3.TestReshape, where TypeParam = caffe::GPUDevice<double>

[  FAILED  ] VideoDataLayerTest/3.TestShuffle, where TypeParam = caffe::GPUDevice<double>

[  FAILED  ] VideoDataLayerTest/3.TestCrop, where TypeParam = caffe::GPUDevice<double>

[  FAILED  ] VideoDataLayerTest/3.TestResize, where TypeParam = caffe::GPUDevice<double>

Now, I just ignore these errors and continue to train the model.
I think it won't be a big issue if I feed the network with frames instead of videos. An I right?

Jimmy

**Comment by chuckcho** [comment]
If you train UCF-101 example, then you're good. In the past, I've seen a bit of issue reading avi files directly (rather than reading extracted frames).

**Comment by lood339** [comment]
Hi Chuckcho,
   A strange problem happened. I have two machines with the same configuration. One machine works well with the code. But the other machine has following error:
  [ RUN      ] ImageDataLayerTest/3.TestResize
*** Aborted at 1476375823 (unix time) try "date -d @1476375823" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x10030) received by PID 28108 (TID 0x7f80fa7b6a00) from PID 65584; stack trace: ***
    @     0x7f80eb666870 (unknown)
    @     0x7f80f2ae1b4d cv::_InputArray::size()
    @     0x7f80f1a3bac7 cv::resize()
    @     0x7f80ebf77687 caffe::ReadImageToCVMat()
    @     0x7f80ec019f74 caffe::ImageDataLayer<>::DataLayerSetUp()
    @     0x7f80ec0e0183 caffe::BasePrefetchingDataLayer<>::LayerSetUp()
    @           0x48af5f caffe::Layer<>::SetUp()
    @           0x7a2021 caffe::ImageDataLayerTest_TestResize_Test<>::TestBody()
    @           0x959793 testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x951597 testing::Test::Run()
    @           0x95163e testing::TestInfo::Run()
    @           0x951745 testing::TestCase::Run()
    @           0x9539d8 testing::internal::UnitTestImpl::RunAllTests()
    @           0x953c67 testing::UnitTest::Run()
    @           0x474aef main
    @     0x7f80eb2d1b05 __libc_start_main
    @           0x47cb79 (unknown)
    @                0x0 (unknown)
Makefile:526: recipe for target 'runtest' failed
make: *** [runtest] Segmentation fault
  The error is from cv::resize() in caffe::ReadImageToCVMat(), then I go through the code. The code looks good to me. 
  As I use the same openCV for the two machines, I suspect there might be some bug before the cv::resize line, but I have no idea where it is.

Jimmy

**Comment by chuckcho** [comment]
OpenCV-related issue. Closing.
