### ISSUE TITLE
Is there any way to convert video frames data to lmdb files?

### ISSUE THREAD

**Issue by G0m3e** [chuckcho/video-caffe#45]
When the train data is too large, the terminal shows that "Data layer prefetch queue empty". So I wanna know is there any possibility to write a tool to convert video frames data to lmdb files, like the original "convert_imageset.cpp" files ? Thanks.

**Comment by chuckcho** [comment]
sorry, don't have a near-term plan to implement that.

**Comment by chuckcho** [comment]
not in plan. closing.

**Comment by MohammadMoradi** [comment]
@chuckcho Hi, I think using lmdb format makes training much faster. Also it is possible to use your branch with DIGITS which is great! Would you please write a tool for that?
