### ISSUE TITLE
error has occured in installation by using apt-installed-CUDNN 

### ISSUE THREAD

**Issue by kazulittlefox** [chuckcho/video-caffe#47]
Hello.
I wanted to try this for action recognition, so I tried to "Cmake install".
but an error has occured and not finished installing.
## The error message said:

```-- Found cuDNN: ver. ??? found (include: /usr/include/cudnn.h, library: /usr/lib/x86_64-linux-gnu/libcudnn*)
CMake Error at cmake/Cuda.cmake:219 (message):
  cuDNN version >3 is required.
Call Stack (most recent call first):
  cmake/Cuda.cmake:247 (detect_cuDNN)
  cmake/Dependencies.cmake:58 (include)
  CMakeLists.txt:43 (include)
---
```
I installed cudnn libraries by using apt .
I suspect that raised this error ... but I have any more clues.

thanks.

**Comment by chuckcho** [comment]
from this message, it looks you don't have CUDNN or right version of it. Usually CUDNN can be downloaded from NVidia website, and directly extracted in `/usr/local` (in case of Linux).
