### ISSUE TITLE
Extracting features

### ISSUE THREAD

**Issue by livst** [chuckcho/video-caffe#50]
I don't understand how the feature extraction works, I mean what really happens there. Is there any difference if i extract the features from iter_2000.caffemodel or iter_200000.caffemodel? Are the features different in any way? 

Another question does features means weights in deep learning?

**Comment by livst** [comment]
So basically to extract the features and classify with some classifier, do I really need to train the network up to some hundred of thousands of iterations?

**Comment by chuckcho** [comment]
you need to have a trained network -- either you train for yourself or get available pre-trained weights.
