### ISSUE TITLE
In example "c3d_ucf101" when train the model it says "Unknown layer type: NdConvolution.."

### ISSUE THREAD

**Issue by yxiao009** [chuckcho/video-caffe#51]
Hi,
I have a problem when I run the example "c3d_ucf101". When I train the model, it says "Unknown layer type: NdConvolution.." It seems missing some types for the N-Dimension Net such as "NdConvolution", "NdPooling" ..., how to fix this?
Any help is appreciated.
Best

**Comment by chuckcho** [comment]
It seems that CuDNN is missing. Can you check?

**Comment by yxiao009** [comment]
Oh, yes, that's the problem. Some packages of cuDNN didn't be installed correctly.
Thank you very much.
