### ISSUE TITLE
where can I find the specific code converting cv_imgs (16xCxHxW) to top[0] (1xCx16xHxW).

### ISSUE THREAD

**Issue by haohao900618** [chuckcho/video-caffe#52]
@chuckcho Dear Chuckcho, thanks for work! I have read the code of VideoDataLayer step by step, but I cannot find the specific code which completes converting vector<cv::Mat> cv_imgs (16xCxHxW) to top(0) (NxCx16xHxW). Can you give me a guider to find the code.  Thanks a lot!

**Comment by chuckcho** [comment]
@haohao900618 VideoDataLayer is derived from BaseDataLayer -- https://github.com/chuckcho/video-caffe/blob/master/src/caffe/layers/data_layer.cpp#L82-L99
