### ISSUE TITLE
I run the train_ucf101.sh file and got an error  as below. What can be the reason for this?

### ISSUE THREAD

**Issue by medhani** [chuckcho/video-caffe#53]
Hi , I got the below error after run train_ucf101.sh and can you help me to solve this

```E1102 14:46:46.984565  4651 caffe.cpp:78] Available caffe actions:
E1102 14:46:46.984985  4651 caffe.cpp:81] 	device_query
E1102 14:46:46.985018  4651 caffe.cpp:81] 	test
E1102 14:46:46.985036  4651 caffe.cpp:81] 	time
E1102 14:46:46.985054  4651 caffe.cpp:81] 	train
F1102 14:46:46.985071  4651 caffe.cpp:83] Unknown action:  
*** Check failure stack trace: ***
    @     0x7fa5dd606f9d  google::LogMessage::Fail()
    @     0x7fa5dd608e03  google::LogMessage::SendToLog()
    @     0x7fa5dd606b2b  google::LogMessage::Flush()
    @     0x7fa5dd6097ee  google::LogMessageFatal::~LogMessageFatal()
    @           0x407402  main
    @     0x7fa5d6f19291  __libc_start_main
    @           0x407c2a  _start
examples/c3d_ucf101/train_ucf101.sh: line 3:  4651 Aborted                 (core dumped) ./build/tools/caffe \ 
examples/c3d_ucf101/train_ucf101.sh: line 5: train: command not found```

**Comment by chuckcho** [comment]
@medhani can you put all the commands in one line and try? it looks you ran `caffe` and `train` in separate lines.

**Comment by chuckcho** [comment]
not video-caffe-related, closing

**Comment by medhani** [comment]
What do you mean by all the commands? I typed examples/c3d_ucf101/train_ucf101.sh

**Comment by medhani** [comment]
I was able to get the below results. How to solve it?

I1103 14:10:56.138675 29608 solver.cpp:404]     Test net output #0: accuracy/top-1 = 0
I1103 14:10:56.156419 29608 solver.cpp:404]     Test net output #1: accuracy/top-5 = 0
I1103 14:10:56.156455 29608 solver.cpp:404]     Test net output #2: loss = 4.42857 (* 1 = 4.42857 loss)
F1103 14:10:56.185187 29608 syncedmem.cpp:56] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
    @     0x7f502a158f9d  google::LogMessage::Fail()
    @     0x7f502a15ae03  google::LogMessage::SendToLog()
    @     0x7f502a158b2b  google::LogMessage::Flush()
    @     0x7f502a15b7ee  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f50311013e8  caffe::SyncedMemory::to_gpu()
    @     0x7f50311004b9  caffe::SyncedMemory::mutable_gpu_data()
    @     0x7f5031249272  caffe::Blob<>::mutable_gpu_data()
    @     0x7f50312ab368  caffe::CudnnNdConvolutionLayer<>::Forward_gpu()
    @     0x7f5031260642  caffe::Net<>::ForwardFromTo()
    @     0x7f5031260757  caffe::Net<>::Forward()
    @     0x7f50310975f0  caffe::Solver<>::Step()
    @     0x7f5031098059  caffe::Solver<>::Solve()
    @           0x40b7b0  train()
    @           0x407440  main
    @     0x7f501ff20291  __libc_start_main
    @           0x407c3a  _start

**Comment by chuckcho** [comment]
it's out of memory (GPU VRAM). reduce `batch_size` in the solver file. for general caffe-related question, you can get answers instantly at:https://groups.google.com/forum/#!forum/caffe-users or https://github.com/BVLC/caffe/issues/
