### ISSUE TITLE
3D CT Perfusion images. How can I best modify the code to suit my purposes? 

### ISSUE THREAD

**Issue by yxiao009** [chuckcho/video-caffe#54]
Hi,
I plan to use video-caffe for CT Perfusion Slices (Grayscale, 3D volume data) which are in matlab format. How can I best modify the code to suit my purposes? 
Any help is appreciated.

**Comment by chuckcho** [comment]
Can you convert your 3D image into frames, and go from there?

**Comment by yxiao009** [comment]
Yes, I have done that, it works well. Thank you.
Now, I would like to do super resolution with 3D images, but the examples here are more like doing classifications with labels.  How can I best modify the code to suit this purposes? I want to have one output with 3D weights and biases (similar as SRCNN and VDSR with 2D outputs). I had tried to modify the net, but result in loss layer dimension mismatch. Check failed: bottom[0]->count(1) == bottom[1]->count(1) (467856 vs. 1)

**Comment by chuckcho** [comment]
Haven't done anything other than classification. Can you try `refactor` branch? It's less hacky implementation, so should have better chance for this.

**Comment by yxiao009** [comment]
OK, I will try it. Thank you.
