### ISSUE TITLE
How to import sequential pictures as an video file from Python wrapper

### ISSUE THREAD

**Issue by kazulittlefox** [chuckcho/video-caffe#55]
Hi

I have successfully installed your video-caffe library, 
and I ran C3D-UCF101 examples for about 25000 iterations.
Then I wanted to test this traind model as classifier for action recognition task.
So I tried to modified the python script which is implemented in default Caffe library,
but I have stacked how to import the sequential pictures as an video data to  this traind model(from python script).

any ideas?

thanks

**Comment by chuckcho** [comment]
Check out [this helper](https://github.com/chuckcho/video-caffe/blob/master/examples/c3d_ucf101/check_data_and_model.py) (currently replicating a single frame to 16-frame clip for simplicity). It should be straight-forward to extend this to a video clip.

**Comment by kazulittlefox** [comment]
Thank you for your reply. It seems so helpful.
