### ISSUE TITLE
Which layers fully support 3D/ND rather than 2D only?

### ISSUE THREAD

**Issue by lynetcha** [chuckcho/video-caffe#56]
I was wondering if all layers available support 3D/ND.
I see that there are Nd implementations of Conv an Pool layers but it is unclear whether the other layers have been adapted to support 3D/Nd. I am specifically interested in Softmax, SoftmaxWithLoss, EltWise, ReLu, Concat,Deconv, and Split Layers.

**Comment by chuckcho** [comment]
Other layers *should* work just as intended. All of the layers you listed -- `Softmax`, `SoftmaxWithLoss`, `EltWise`, `ReLu`, `Concat`, `Deconv` and `Split` -- don't require a bottom blob to be of any particular dimension.

**Comment by xjtuljy** [comment]
Thanks @chuckcho it's a great job! I also want to use "deconv" and "EuclideanLoss" layer. But I wonder how shall I define it's parameters, shall I just do as follows for a 3D deconvolution:

convolution_param {
    num_output: 64
    kernel_size: 2
    kernel_size: 2
    kernel_size: 2
    stride_size: 2
    stride_size: 2
    stride_size: 2
}

Any help is appreciated.
