### ISSUE TITLE
Who can train the net correctly by the GTX1080

### ISSUE THREAD

**Issue by fanguu** [chuckcho/video-caffe#57]
I found  the GTX1080 needs the CUDA8.0 and the cuDNN5.0 or more higher version, if CUDA7.5 and cuDNN4.0 was used  the code would give series error. For example, the loss can't be decreased and keep around 4.7 ,So who can give the new code that  could be run by the cuDNN5.0 ro5.1. Thanks a lot. @chuckcho

**Comment by chuckcho** [comment]
Tested `refactor` branch with `1080 + CUDA v8.0 + CuDNN v5.1.5`. Should work fine. Please try `refactor` version -- it's less hacky and faster than the `master` version.

**Comment by fanguu** [comment]
Thank you. I will test it.
