### ISSUE TITLE
Check failed: status == CUDNN_STATUS_SUCCESS (9 vs. 0)  CUDNN_STATUS_NOT_SUPPORTED

### ISSUE THREAD

**Issue by medhani** [chuckcho/video-caffe#58]
I was running a video synthesis code by using video-caffe. Once I included "force backward=true" on prototxt file it gave an error as below.

cudnn_ndconv_layer.cu:184] Check failed: status == CUDNN_STATUS_SUCCESS (9 vs. 0)  CUDNN_STATUS_NOT_SUPPORTED

Can you please let me know the reason behind this error?

**Comment by chuckcho** [comment]
haven't tried `force_backward`. can you use `refactor` branch to see if this error goes away? this branch is cleaner and less hacky implementation of nd conv/pooling.

**Comment by medhani** [comment]
I'm sorry for asking I'm new to caffe and python. Can you please explain me what is refactor branch?

**Comment by chuckcho** [comment]
@medhani refactor branch: https://github.com/chuckcho/video-caffe/tree/refactor (after cloning, do `git checkout refactor`)

**Comment by medhani** [comment]
I got this error after refactor branch


WARNING: Logging before InitGoogleLogging() is written to STDERR
W1121 14:05:29.393661 20809 _caffe.cpp:122] DEPRECATION WARNING - deprecated use of Python interface
W1121 14:05:29.393704 20809 _caffe.cpp:123] Use this instead (with the named "weights" parameter):
W1121 14:05:29.393717 20809 _caffe.cpp:125] Net('/home/medhani/DeepTextures_noback_16Nov2016/examples/c3d_ucf101/c3d_ucf101_deploy.prototxt', 1, weights='/home/medhani/DeepTextures_noback_16Nov2016/examples/c3d_ucf101/c3d_ucf101_iter_38000.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 28:18: Message type "caffe.ConvolutionParameter" has no field named "kernel_shape".
F1121 14:05:29.398283 20809 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /home/medhani/DeepTextures_noback_16Nov2016/examples/c3d_ucf101/c3d_ucf101_deploy.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by medhani** [comment]
I was able to do cmake and make test successfully. But I got the below error when I did " sh /examples/c3d_ucf101/test_ucf101.sh

I1122 16:37:17.261770 26133 layer_factory.hpp:77] Creating layer data
I1122 16:37:17.261821 26133 net.cpp:100] Creating Layer data
I1122 16:37:17.261837 26133 net.cpp:408] data -> data
I1122 16:37:17.261873 26133 net.cpp:408] data -> label
I1122 16:37:17.261907 26133 data_transformer.cpp:25] Loading mean file from: examples/c3d_ucf101/ucf101_train_mean.binaryproto
F1122 16:37:17.295440 26133 blob.cpp:478] Check failed: count_ == proto.data_size() (6144 vs. 0) 
*** Check failure stack trace: ***
    @     0x7f92b068bf9d  google::LogMessage::Fail()
    @     0x7f92b068de03  google::LogMessage::SendToLog()
    @     0x7f92b068bb2b  google::LogMessage::Flush()
    @     0x7f92b068e7ee  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f92b18640e0  caffe::Blob<>::FromProto()
    @     0x7f92b187e3d9  caffe::DataTransformer<>::DataTransformer()
    @     0x7f92b18a6339  caffe::BaseDataLayer<>::LayerSetUp()
    @     0x7f92b18a6473  caffe::BasePrefetchingDataLayer<>::LayerSetUp()
    @     0x7f92b19df673  caffe::Net<>::Init()
    @     0x7f92b19e10b0  caffe::Net<>::Net()
    @           0x409f94  test()
    @           0x408123  main
    @     0x7f929e75f291  __libc_start_main
    @           0x408aba  _start

**Comment by pelun** [comment]
@chuckcho .Can you help me?
When I ran make all to build_release, it appeared warning:
NVCC src/caffe/solvers/adadelta_solver.cu
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
NVCC src/caffe/solvers/adam_solver.cu
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
NVCC src/caffe/solvers/rmsprop_solver.cu
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).

**Comment by chuckcho** [comment]
@pelun This looks like warnings, not errors.

**Comment by pelun** [comment]
'may be removed in a future release'. I worry.

**Comment by pelun** [comment]
I'm using refactor branch, but that still happen the same error when trained:

F1202 20:20:17.346976  1925 math_functions.cu:375] Check failed: status == CURAND_STATUS_SUCCESS (102 vs. 0)  CURAND_STATUS_ALLOCATION_FAILED
*** Check failure stack trace: ***
    @     0x7feb9d2665cd  google::LogMessage::Fail()
    @     0x7feb9d268433  google::LogMessage::SendToLog()
    @     0x7feb9d26615b  google::LogMessage::Flush()
    @     0x7feb9d268e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7feb9da6dcaa  caffe::caffe_gpu_rng_uniform()
    @     0x7feb9da7e7c2  caffe::DropoutLayer<>::Forward_gpu()
    @     0x7feb9da54582  caffe::Net<>::ForwardFromTo()
    @     0x7feb9da546a7  caffe::Net<>::Forward()
    @     0x7feb9d8e0f10  caffe::Solver<>::Step()
    @     0x7feb9d8e19a9  caffe::Solver<>::Solve()
    @           0x40bd89  train()
    @           0x4077c8  main
    @     0x7feb9b9fd830  __libc_start_main
    @           0x408099  _start
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by dasabir** [comment]
With help from @ronghanghu we saw that 'bwd_data_algo_' (used in [Line 181 of cudnn_ndconv_layer.cu](https://github.com/chuckcho/video-caffe/blob/master/src/caffe/layers/cudnn_conv_layer.cu#L181)) is declared ([Line 123, 124 of cudnn_ndconv_layer.cpp](https://github.com/chuckcho/video-caffe/blob/master/src/caffe/layers/cudnn_ndconv_layer.cpp#L123-L124)) but never set. Following caffe's cudnn_conv_layer.cpp if we add the last two lines after [line 140 of cudnn_ndconv_layer.cpp](https://github.com/chuckcho/video-caffe/blob/master/src/caffe/layers/cudnn_ndconv_layer.cpp#L140) so that the block "// Create tensor descriptor(s) for data and corresponding convolution(s)." now becomes the following, then the code runs.
```
for (int i = 0; i < bottom.size(); i++) {
    cudnnTensorDescriptor_t bottom_desc;
    cudnn::createTensorDesc<Dtype>(&bottom_desc);
    bottom_descs_.push_back(bottom_desc);
    cudnnTensorDescriptor_t top_desc;
    cudnn::createTensorDesc<Dtype>(&top_desc);
    top_descs_.push_back(top_desc);
    cudnnConvolutionDescriptor_t conv_desc;
    cudnn::createConvolutionDesc<Dtype>(&conv_desc);
    conv_descs_.push_back(conv_desc);
    workspace_bwd_data_sizes_[i] = 0;
    workspace_bwd_filter_sizes_[i] = 0;
    bwd_filter_algo_[i] = (cudnnConvolutionBwdFilterAlgo_t)0;
    bwd_data_algo_[i] = (cudnnConvolutionBwdDataAlgo_t)0;
  }
```

**Comment by chuckcho** [comment]
@dasabir @ronghanghu thanks for your contribution (and sorry for late reply). i just merged this change.
