### ISSUE TITLE
Can Video-caffe run with CPU_ONLY=1?

### ISSUE THREAD

**Issue by nvanthuy** [chuckcho/video-caffe#59]
Hi, 

I only have MacPro 13' 2015, with no GPU support, OS 10.12 Sierra. Can I try to run Video-caffe with CPU_only, and no CUDnn to see how it work with some sample data? 

Many thanks,

nvanthuy

**Comment by livst** [comment]
Hi,

Video-caffe can't run in CPU_ONLY mode, for now. It may be possible in the newer version.

**Comment by chuckcho** [comment]
@nvanthuy Sorry -- currently `video-caffe` needs GPU.
