### ISSUE TITLE
How to disgard frames less than 16

### ISSUE THREAD

**Issue by AnshanTJU** [chuckcho/video-caffe#61]
Hi,all,
The video-caffe code crashed for less than 16 frames in io.cpp. Any one can tell me how to disgard the frames less than 16?

E1124 16:08:25.401106 20080 io.cpp:196] not enough frames; num_frames=237, start_frame=225, length=16
F1124 16:08:25.401816 20080 video_data_layer.cpp:145] Check failed: read_video_result Could not load /export/anshan/video/data/UCF-101/SoccerJuggling/v_SoccerJuggling_g05_c02.avi at frame 225.
*** Check failure stack trace: ***
    @     0x7ffbd83a084d  google::LogMessage::Fail()
    @     0x7ffbd83a261c  google::LogMessage::SendToLog()
    @     0x7ffbd83a043c  google::LogMessage::Flush()

**Comment by livst** [comment]
From the description:

> Optional) video reader works more stably with extracted frames than directly with video files. Extract frames from UCF-101 videos by revising and running a helper script, ${video-caffe-root}/examples/c3d_ucf101/extract_UCF-101_frames.sh.
> Change ${video-caffe-root}/examples/c3d_ucf101/c3d_ucf101_{train,test}_split1.txt to correctly point to UCF-101 videos or directories that contain extracted frames

**Comment by chuckcho** [comment]
@AnshanTJU it shouldn't be difficult to implement the logic to ignore video clip that doesn't have 16 frames. or, you could preprocess the train/test clip list files to check extracted frames and remove video clips that are incomplete.
