### ISSUE TITLE
How to use the pre-trained model which was trained on sport 1M dataset?

### ISSUE THREAD

**Issue by bitwangdan** [chuckcho/video-caffe#66]
I run the code successfully. the model is pre-trained on the ucf_101 dataset ,but when i replace it with a model pre-trained on the sport1M dataset ,the code was wrong , can you tell me how to deal with it ?

**Comment by pelun** [comment]
After I train this model, I run plot_training_loss.sh. It shows:

[Error] Can not find a log file.
[Error] A valid filename should match *_{log|train}.txt or *.log.
[Error] Alternatively, specify log file(s) as input arg (wildcard permitted). Exitting.

Help me resolved this problem, please!

**Comment by pelun** [comment]
@chuckcho Can you help me?

**Comment by xuzhenqi** [comment]
I also have the need to use the pre-trained model from sport1M dataset, since it performs better. It's convenient if this repo contains such examples.

**Comment by pelun** [comment]
@xuzhenqi  Can you help me resolved errors above?

**Comment by chuckcho** [comment]
@pelun your question (https://github.com/chuckcho/video-caffe/issues/66#issuecomment-264759702) is not related to the original question. `plot_training_loss` is quite hacky, and assumes many things (python packages, directory / filenaming, etc). Look at the file to resolve your case please.

**Comment by chuckcho** [comment]
@bitwangdan sorry for the late reply. When you say `model pre-trained on the sport1M dataset`, what exactly is it? Isn't that model trained using facebook/C3D? Then, it's not compatible.

**Comment by bitwangdan** [comment]
@chuckcho  Hi, in this example ,you only offer the code about the ucf101, but the sport 1M hava a good result on the feature extraction , can you offer the code about the sport 1M , i need your help.

**Comment by chuckcho** [comment]
I'll try to convert sports1M pre-trained model into the format that's useable here. Please bear with me.

**Comment by LongLong-Jing** [comment]
@chuckcho  Can you give me some hint about how to convert Sport1M pre-trained model to the format that I can use here? If I know how to do it, I can try to convert the model. Thanks!

**Comment by chuckcho** [comment]
i'll do the conversion in my spare time. Moved this issue to TODO list in README.md for now. Thanks.
