### ISSUE TITLE
run a demo

### ISSUE THREAD

**Issue by dehaisea** [chuckcho/video-caffe#69]
I only know how to extract features from a video. But if there is a script to run a video demo like shown on the website "http://www.cs.dartmouth.edu/~dutran/c3d/" ? Thanks a lot.

**Comment by chuckcho** [comment]
No. It will involve extract video clips, run through classification, overlay classification results on images, assemble them together into a video -- straight-forward, but time-consuming to actually implement this.

**Comment by pelun** [comment]
But, how to assign label for video?

**Comment by pelun** [comment]
I made a demo. First, I extract video clips, classify on image and then I chose the popular label to make a label for video. 
Is it OK?

**Comment by chuckcho** [comment]
sounds fine.

**Comment by pelun** [comment]
Thanks. But, I haven't treated the signal temporal.

**Comment by chuckcho** [comment]
Classification is based on one frame only? -- that still works, but won't be as good to classify motion-based concepts as the C3D.

**Comment by pelun** [comment]
Thanks. How can I make this project have a good results?

**Comment by pelun** [comment]
@chuckcho. I can not show a label to predict class.

**Comment by chuckcho** [comment]
@pelun Can you elaborate please?

**Comment by pelun** [comment]
Ohh. I run test_ucf101.sh file with a single video, but it isn't show the label on terminal.

**Comment by chuckcho** [comment]
I see your point. `test_ucf101.sh` does show top-1 accuracy only. I'll add a python code to predict a class for a given video clip (or a whole video file) in a near future. Thanks.
