### ISSUE TITLE
questions about C3D model fine-tuned on UCF101

### ISSUE THREAD

**Issue by hayato8059** [chuckcho/video-caffe#70]
thank you to share the C3D code. In C3D User Guide you provide the C3D model fine-tuned on UCF101 on https://www.dropbox.com/s/mkc9q7g4wnqnmcv/c3d_ucf101_finetune_whole_iter_20000 this web, but i can't open this. Is this website have some problems?

**Comment by chuckcho** [comment]
I can have an access now -- it's possible accessibility could depend on geolocation.

**Comment by hayato8059** [comment]
I have a vpn, but still can't open this web. can i get this model with other ways? like E-mail?  
my E-mail is amenokaze13@126.com
thank you.

**Comment by chuckcho** [comment]
@hayato8059 how about this? https://docs.google.com/uc?id=0B4uwFi8qXwi5T1ZsY3hYTE1XUVk&export=download

**Comment by hayato8059** [comment]
I can open it! thank you very much!!
