### ISSUE TITLE
question about test c3d_ucf101_finetune_whole_iter_20000 model

### ISSUE THREAD

**Issue by hayato8059** [chuckcho/video-caffe#73]
Thank you for share this model on Google cloud disk.
when i test this model, have a error:
Cannot copy param 0 weights from layer 'conv1a'; shape mismatch.  Source param shape is 64 3 3 3 3 (5184); target param shape is 64 3 3 3 3 (5184). To learn this layer's parameters from scratch rather than copying from a saved net, rename the layer.
Source param shape the same with  target param shape, but shape mismath?

**Comment by nvanthuy** [comment]
Same to me. I also have this problem. Have anyone tried this model successfully? 

Thanks.

**Comment by LongLong-Jing** [comment]
When I use the Sport-1M pre-trained model, I got the same error. @hayato8059, @nvanthuy , have you solved this problem?

**Comment by chuckcho** [comment]
this problem should be gone with the latest model I just uploaded. closing.
