### ISSUE TITLE
finetuning the pretrained model sport1m on UCF101

### ISSUE THREAD

**Issue by jiang2764** [chuckcho/video-caffe#74]
I were trying to use the pretrained model on Sports1M provided on webpage: http://vlg.cs.dartmouth.edu/c3d/
I got the following error using video-caffe. Can you provide me some info about how to use this pretrained model?

I1209 12:21:56.175815 96677 upgrade_proto.cpp:53] Attempting to upgrade input file specified using deprecated V1LayerParameter: /nfs/abc/utilities/C3D/examples/c3d_finetuning/conv3d_deepnetA_sport1m_iter_1900000
I1209 12:21:56.572003 96677 upgrade_proto.cpp:61] Successfully upgraded file specified using deprecated V1LayerParameter
F1209 12:21:56.590073 96677 blob.cpp:478] Check failed: count_ == proto.data_size() (1728 vs. 0) 
*** Check failure stack trace: ***
    @     0x2afad47d6efd  google::LogMessage::Fail()
    @     0x2afad47d8cb3  google::LogMessage::SendToLog()
    @     0x2afad47d6b18  google::LogMessage::Flush()
    @     0x2afad47d950e  google::LogMessageFatal::~LogMessageFatal()
    @     0x2aface45b6d7  caffe::Blob<>::FromProto()
    @     0x2aface5998c4  caffe::Net<>::CopyTrainedLayersFrom()
    @     0x2aface599b95  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x2aface59f561  caffe::Net<>::CopyTrainedLayersFrom()
    @           0x40ad96  CopyLayers()
    @           0x40b7fd  train()
    @           0x4074c4  main
    @       0x360001ed5d  (unknown)
    @           0x407be5  (unknown)

**Comment by chuckcho** [comment]
Sorry. Model created from https://github.com/facebook/C3D is not directly useable in this version of caffe as there are many differences in implementation details. When and if I successfully convert this Sports1m pretrained model into `video-caffe` format, I'll let you know and also update README.

**Comment by InnovArul** [comment]
@jiang2764  Were you able overcome this issue of **Check failed: count_ == proto.data_size() (1728 vs. 0)**? Could you please share the solution to solve that?

Thanks!

**Comment by jiang2764** [comment]
@InnovArul I think you should use the latest converted sport1m model for video-caffe. You should be able to find it in one of issue pages.
