### ISSUE TITLE
How to get my own train_mean.binaryproto by the caffe?

### ISSUE THREAD

**Issue by fanguu** [chuckcho/video-caffe#76]
I want to know how to make rain_mean.binaryproto of my data sets, and I want to make sure that the three mean values are R,G and B channel respectively in the train_test.prototxt. 
![qq 20161211153108](https://cloud.githubusercontent.com/assets/21071524/21078799/00c586ea-bfb7-11e6-91f5-f1f2ad109101.png)

**Comment by chuckcho** [comment]
look at the [original C3D author's note](https://docs.google.com/document/d/1-QqZ3JHd76JfimY4QKqOojcEaf5g3JS0lNh-FHTxLag/edit) to generate a mean cube. it turns out that just RGB mean pixel values are sufficient.
