### ISSUE TITLE
How to get test result for single video?

### ISSUE THREAD

**Issue by JinJunho** [chuckcho/video-caffe#77]
I've trained my own model and now I want to get test result for single video but have no idea how to achieve it. I've found an article using caffe.io.Transformer for preprocessing images, but I don't think it will work for video input. Any guide or help on how to do this? I am using pycaffe now by the way.

**Comment by chuckcho** [comment]
sorry for the late reply. the idea will be (1) assembling 16-frame video clip from a video, (2) run

**Comment by JinJunho** [comment]
Thank you. Following some articles I made it :-)

**Comment by chuckcho** [comment]
You're welcome. Feel free to contribute to this project by making a PR.

**Comment by kpuuu** [comment]
@JinJunho  Hi, can you tell me how you make the code, im trying to make the same thing and i don't understand how to make the code. U u
