### ISSUE TITLE
receive error after run c3d_ucf101(train)

### ISSUE THREAD

**Issue by RORO11** [chuckcho/video-caffe#78]
![videoread](https://cloud.githubusercontent.com/assets/24369303/21218312/06114d0a-c2eb-11e6-8c1c-404d738b714c.png)
thank you for helping

**Comment by chuckcho** [comment]
looks like forward slash vs backward slash thing. in windows, it should be backward `\`. make sure you have all the extracted frames. or, it could be opencv issue.

**Comment by RORO11** [comment]
I have solve that problem,but I receive new problem,please help me
![video](https://cloud.githubusercontent.com/assets/24369303/21290877/b45936da-c506-11e6-8b87-9afe0e06e9dd.png)

**Comment by chuckcho** [comment]
Let me know if you weren't able to address this. For now, I'll have this closed.
