### ISSUE TITLE
cpp prediction sample

### ISSUE THREAD

**Issue by twtygqyy** [chuckcho/video-caffe#82]
Anyone who can provide a simple cpp version of prediction code? Thanks in advance.

**Comment by twtygqyy** [comment]
I tried to modify the image classification sample for c3d, however, I got the error because the caffe::Blob<Dtype>cannot support (num, channel, length, h, w) reshape.
How can to send the image data into the networks?

**Comment by chuckcho** [comment]
@twtygqyy can you give me more specifics? network architecture prototxt, e.g.?

**Comment by twtygqyy** [comment]
@chuckcho Thanks for the reply, here is the prototxt
[deploy.txt](https://github.com/chuckcho/video-caffe/files/692760/deploy.txt)

It works when I use python API, concatenate multiple images and send the data into the networks. However, when I try to implement the prediction function in cpp, I have not idea how to initialize the input layer and also Reshape the blob dimension

**Comment by twtygqyy** [comment]
@chuckcho BTW, does predict.cpp work for refactor branch?

**Comment by MohammadMoradi** [comment]
@chuckcho Hi, I really appreciate your job but I think it would be a great idea to provide a simple example.  Without implementation the trained models are not much useful.
Thanks in advance

**Comment by chuckcho** [comment]
Working on it. Close for now.
