### ISSUE TITLE
Does Video-Caffe support voxel segmentation?

### ISSUE THREAD

**Issue by ltnghia** [chuckcho/video-caffe#83]
Hi,

I work on video segmentation. I wonder if this caffe version can support 3D layers such as **3D Deconvolution**, **voxel_wise_softmax_layer**, **voxel_wise_softmax_loss_layer**, **video_segmentation_data_layer** as in [C3D Caffe](https://github.com/facebook/C3D/tree/master/src/caffe/layers).

How can I adapt these layers from C3D Caffe to this Video-Caffe?

Thank you in advance.

**Comment by chuckcho** [comment]
Haven't implemented video segmentation. Will need some effort for that.

**Comment by chuckcho** [comment]
Will revisit as needed.
