### ISSUE TITLE
How to extract the feature in the C3D net?

### ISSUE THREAD

**Issue by fanguu** [chuckcho/video-caffe#84]
I want to plot the pictures of my data feature embedding visualization, but there are some problems, how to get the feature in the net , like layer fc7 or layer fc8, then  I want to know If the t-SNE can be used to draw the picture. If it can not, which codes can be used?

![111](https://cloud.githubusercontent.com/assets/21071524/21971264/cd4e9f3c-dbe9-11e6-9cb5-0a6a966924f9.png)

**Comment by chuckcho** [comment]
please check out https://github.com/chuckcho/video-caffe/blob/master/examples/c3d_ucf101/feature_extraction/extract_c3d_features.sh ?

**Comment by medhini** [comment]
I tried to run extract_c3d_features.sh and I get the following error:

Check failed: error == cudaSuccess (10 vs. 0)  invalid device ordinal

How do i fix this?

**Comment by chuckcho** [comment]
I'll soon fix the feature extraction script.
