### ISSUE TITLE
How can I compile it for Windows?

### ISSUE THREAD

**Issue by mixtoism** [chuckcho/video-caffe#85]
I've seen that Caffe now supports windows, but since this fork includes new files, I'm not sure, how should I compile them to be compatible with Windows.

**Comment by chuckcho** [comment]
haven't tried on Windows. If Caffe supports Windows, I don't see why video-caffe can't work in Windows. Have you encountered any issue building in Win?

**Comment by mixtoism** [comment]
Actually is a special build of Caffe the one that is suitable for Windows
