### ISSUE TITLE
Error while extracting c3d features

### ISSUE THREAD

**Issue by medhini** [chuckcho/video-caffe#90]
I tried running extract_c3d_features.sh and I get the following error:

E0212 18:47:51.618083  9049 io.cpp:169] Could not open or find file /media/TB/UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c01

F0212 18:47:51.618093  9049 video_data_layer.cpp:77] Check failed: read_video_result Could not load /media/TB/UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c01 at frame 1.

How do I go about fixing this? Also, how do I extract c3d features for my videos?

**Comment by yangzhikai** [comment]
me too. have you solved it?

**Comment by chuckcho** [comment]
i'll double check this script.

**Comment by chuckcho** [comment]
i moved this item to TODO list. will address soon.
