### ISSUE TITLE
Impement in latest caffe

### ISSUE THREAD

**Issue by oyxhust** [chuckcho/video-caffe#91]
If I want to add the nd conv layer and pooling layer to the latest caffe, what files shoud I add to the latest caffe?

**Comment by oyxhust** [comment]
When I add to the latest caffe, make all and make test is both ok, but when Ｉ make runtest, an error appears:
 AdamSolverTest/3.TestSnapshot
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.SolverParameter: 1:113: Message type "caffe.SolverParameter" has no field named "layer_wise_reduce".
F0217 10:23:40.459079 27474 test_gradient_based_solver.cpp:56] Check failed: google::protobuf::TextFormat::ParseFromString(proto, &param) 
*** Check failure stack trace: ***
    @     0x7fb58921c5cd  google::LogMessage::Fail()
    @     0x7fb58921e433  google::LogMessage::SendToLog()
    @     0x7fb58921c15b  google::LogMessage::Flush()
    @     0x7fb58921ee1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x608253  caffe::GradientBasedSolverTest<>::InitSolverFromProtoString()
    @           0x5f23b7  caffe::GradientBasedSolverTest<>::RunLeastSquaresSolver()
    @           0x5f70ed  caffe::GradientBasedSolverTest<>::TestSnapshot()
    @           0x5f8d73  caffe::AdamSolverTest_TestSnapshot_Test<>::TestBody()
    @           0x91d403  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x916a1a  testing::Test::Run()
    @           0x916b68  testing::TestInfo::Run()
    @           0x916c45  testing::TestCase::Run()
    @           0x917f1f  testing::internal::UnitTestImpl::RunAllTests()
    @           0x918243  testing::UnitTest::Run()
    @           0x46d0bd  main
    @     0x7fb583a31830  __libc_start_main
    @           0x474bb9  _start
    @              (nil)  (unknown)
Makefile:532: recipe for target 'runtest' failed
make: *** [runtest] Aborted (core dumped)

**Comment by r123r123** [comment]
Have you solved the problem?

**Comment by oyxhust** [comment]
@r123r123 facebook has updated their C3D into the latest caffe, please check this one: https://github.com/facebook/C3D/tree/master/C3D-v1.1
