### ISSUE TITLE
How is convolution computed over sequences?

### ISSUE THREAD

**Issue by Nunah** [chuckcho/video-caffe#92]
Hi,

I'm using the master branch (because I need the python wrapper to make python layers) and it works pretty well. Thank you for sharing your implementation!

But I'm not sure to understand how the convolution is performed over sequences. For example, with a 3x4x64x64 (CxLxHxW) input through this conv : 

layer {
    name: "conv1a"
    type: "NdConvolution"
    bottom: "data1"
    top: "conv1a"
    param {
        lr_mult: 1
        decay_mult: 1
    }
    param {
        lr_mult: 2
        decay_mult: 0
    }
    convolution_param {
        num_output: 16                                      
        kernel_shape { dim: 3 dim: 5 dim: 5 }        
        stride_shape { dim: 1 dim: 1 dim: 1 }                                       
        pad_shape    { dim: 1 dim: 2 dim: 2 }                                                
        weight_filler {
            type: "xavier" 
            std: 0.1
        }
        bias_filler {
            type: "constant"
            value: 0.2
        }
    }
}

I got the following error : CUDNN_STATUS_SUCCESS (3 vs. 0) CUDNN_STATUS_BAD_PARAM
But if I change pad_shape { dim: 2 dim: 2 dim: 2 }, it works!

I got the same error with : 

kernel_shape { dim: 5 dim: 5 dim: 5 }        
stride_shape { dim: 1 dim: 1 dim: 1 }                                       
pad_shape    { dim: 2 dim: 2 dim: 2 }

Can somebody tell me what I am doing wrong?

**Comment by LongLong-Jing** [comment]
Please refer to this paper about how 3D Convolutions works. 
http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=6165309

**Comment by Nunah** [comment]
Thank you very much!
