### ISSUE TITLE
Pretrained caffemodels and prototxt files missing

### ISSUE THREAD

**Issue by vivoutlaw** [chuckcho/video-caffe#95]
@chuckcho,@lood339: Hi, the links to download the pretrained vodels for VGG, and other shared by you and other are missing. Can you please share the pretrained models trained on Sports1m or UCF101 with its prototxt files? Thanks!
best, Vivek

**Comment by lood339** [comment]
Can you have a try of this: 
model: https://www.dropbox.com/s/lwdg0r09af6b83g/c3d_ucf101_iter_38000.caffemodel?dl=0
deploy file: https://www.dropbox.com/s/4wdaj5oiml6avqw/c3d_ucf101_deploy.prototxt?dl=0

**Comment by vivoutlaw** [comment]
thanks, @lood339! :)

**Comment by lood339** [comment]
My pleasure. Can you report the testing accuracy using this model? Some people say they had lower accuracy (around 20%) on test, which is much lower than I had. Thanks.

**Comment by vivoutlaw** [comment]
@lood339: OK, I'll let you know about it. :)

**Comment by chuckcho** [comment]
i recently rebased on the latest caffe, and did a fresh training from scratch: https://www.dropbox.com/s/gglm2c67154nltr/c3d_ucf101_iter_20000.caffemodel?dl=0 should get ~47% test accuracy

**Comment by chuckcho** [comment]
will be documented soon in README. closing
